"""
Builds downloadable prediction reports.

Turns a supplier's live prediction into files a person can share:
  - Markdown / text summary report
  - CSV of the prediction and its risk factors
"""

from __future__ import annotations  # Modern type hint support

from datetime import datetime  # Timestamp on each report

import pandas as pd  # Tables

from src.services.prediction_service import SupplierPrediction


def build_prediction_report_markdown(
    prediction: SupplierPrediction,
    actions: list[dict[str, str]],
    factors: pd.DataFrame | None = None,
    model_metrics: dict | None = None,
) -> str:
    """
    Create a human-readable report for one supplier.

    Written in plain language so a manager can read it without help.
    """
    p = prediction
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")

    risk_level = (
        "HIGH" if p.delay_probability >= 0.7
        else "MEDIUM" if p.delay_probability >= 0.4
        else "LOW"
    )

    lines: list[str] = [
        "# Supplier Disruption Report",
        "",
        f"**Generated:** {generated}",
        f"**Supplier:** {p.supplier_name} ({p.supplier_id})",
        f"**Region:** {p.region}",
        f"**Category:** {p.category}",
        f"**Data as of:** {p.as_of_date}",
        "",
        "## Prediction",
        "",
        f"- **Result:** {p.prediction_label}",
        f"- **Risk level:** {risk_level}",
        f"- **Chance of disruption:** {p.delay_probability:.0%}",
        f"- **Model confidence:** {p.confidence:.0%}",
        "",
        "## Current Numbers",
        "",
        f"| Measure | Value |",
        f"|---------|-------|",
        f"| Risk score | {p.risk_score:.0f} / 100 |",
        f"| Lead time | {p.lead_time_days:.0f} days |",
        f"| Inventory coverage | {p.inventory_coverage_days:.0f} days |",
        f"| Sentiment score | {p.sentiment_score:.2f} (0 = bad news, 1 = good news) |",
        f"| On-time delivery | {p.reliability:.0%} |",
        f"| Negative news (7 days) | {p.negative_news_count} |",
        "",
    ]

    if factors is not None and not factors.empty:
        lines.extend(["## Top Risk Factors", ""])
        ordered = factors.sort_values("abs_impact", ascending=False)
        for _, row in ordered.iterrows():
            direction = "increases risk" if row["Impact"] > 0 else "reduces risk"
            lines.append(f"- **{row['Factor']}** — {direction}")
        lines.append("")

    lines.extend(["## Recommended Actions", ""])
    if actions:
        for action in actions:
            marker = {"urgent": "[URGENT]", "watch": "[WATCH]", "ok": "[OK]"}.get(
                action.get("level", "ok"), "[INFO]"
            )
            lines.append(f"- {marker} {action['text']}")
    else:
        lines.append("- No action needed right now.")
    lines.append("")

    if model_metrics:
        lines.extend(
            [
                "## Model Quality",
                "",
                f"- Accuracy: {model_metrics.get('accuracy', 0):.0%}",
                f"- Precision: {model_metrics.get('precision', 0):.2f}",
                f"- Recall: {model_metrics.get('recall', 0):.2f}",
                f"- F1 score: {model_metrics.get('f1', 0):.2f}",
                f"- ROC-AUC: {model_metrics.get('roc_auc', 0):.2f}",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "_Generated by the AI Supply Chain Disruption Predictor._",
            "_Predictions are estimates and should support, not replace, human judgement._",
        ]
    )

    return "\n".join(lines)


def build_prediction_report_csv(
    prediction: SupplierPrediction,
    factors: pd.DataFrame | None = None,
) -> str:
    """Create a CSV version of one supplier's prediction."""
    rows: list[dict[str, object]] = []
    for key, value in prediction.as_dict().items():
        rows.append({"section": "prediction", "name": key, "value": value})

    if factors is not None and not factors.empty:
        ordered = factors.sort_values("abs_impact", ascending=False)
        for _, row in ordered.iterrows():
            rows.append(
                {
                    "section": "risk_factor",
                    "name": row["Factor"],
                    "value": round(float(row["Impact"]), 4),
                }
            )

    return pd.DataFrame(rows).to_csv(index=False)


def build_all_predictions_csv(predictions_df: pd.DataFrame) -> str:
    """Create a CSV of every supplier's latest prediction."""
    if predictions_df.empty:
        return "supplier_id,delay_probability\n"
    return predictions_df.to_csv(index=False)
